plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '9.5.1'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.commons:commons-csv:1.14.1'

    String junitVersion = '5.14.4'
    testImplementation "org.junit.jupiter:junit-jupiter-api:${junitVersion}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${junitVersion}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.14.4'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

test {
    useJUnitPlatform()

    testLogging {
        events 'passed', 'skipped', 'failed'
        showExceptions = true
        exceptionFormat = 'full'
        showCauses = true
        showStackTraces = true
        showStandardStreams = false
    }
}

application {
    mainClass = 'luckynoslacky.LuckyNoSlacky'
}

jar {
    // A lean JAR file is not needed because the shadow JAR includes dependencies.
    enabled = false
    archiveClassifier = 'without-dependencies'
}

shadowJar {
    archiveFileName = 'luckyNoSlacky.jar'

    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
}

run {
    standardInput = System.in
}
